//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNet.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPermissions
    {
        public AccountPermissions()
        {
            this.AccountPermission_Accounts = new HashSet<Accounts>();
            this.Permissions = new HashSet<Permissions>();
        }
    
        public int Id { get; set; }
        public string AccoutId { get; set; }
        public string PermissionId { get; set; }
        public string Timestamp { get; set; }
    
        public virtual ICollection<Accounts> AccountPermission_Accounts { get; set; }
        public virtual ICollection<Permissions> Permissions { get; set; }
    }
}
