//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNet.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public Accounts()
        {
            this.EmailVerified = false;
            this.Account_PermissionAccounts = new HashSet<AccountPermissions>();
            this.Terms = new HashSet<Terms>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public bool EmailVerified { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public System.TimeSpan Timestamp { get; set; }
        public Nullable<int> TermId { get; set; }
        public System.DateTime AgreedToTermsDate { get; set; }
    
        public virtual ICollection<AccountPermissions> Account_PermissionAccounts { get; set; }
        public virtual ICollection<Terms> Terms { get; set; }
    }
}
