//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNet.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissions
    {
        public Permissions()
        {
            this.Permissions_AccountPermissions = new HashSet<AccountPermissions>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Timestamp { get; set; }
    
        public virtual ICollection<AccountPermissions> Permissions_AccountPermissions { get; set; }
    }
}
