//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNet.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terms
    {
        public int Id { get; set; }
        public string Term { get; set; }
        public string Timestamp { get; set; }
        public int AccountsId { get; set; }
    
        public virtual Accounts Account { get; set; }
    }
}
